### ISSUE TITLE
Doubled cards

### ISSUE THREAD

**Issue by robsontenorio** [Tidwell/faeria-cards#1]
Hi,  "merlin" has doubled cards. How to recognize the active one? By looking text, CARD_ID = 313 is the newest.

http://tidwell.github.io/faeria-cards/
Ex: twinsoul

**Comment by Tidwell** [comment]
Just in case anyone else stumbles on this, the duplicates (like twinsoul) are generally the generated cards (ie. twinsoul actually generates a different card, not a real copy of itself).  Cards that are uncollectible have a codexId of 106666.

**Comment by robsontenorio** [comment]
Thanks! Great info:)
